name = "KasuKasualPack"
author = "Kasualidad"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9a0d0999734b71d65a17f81c2dcf19c59630e830c74f74f6b19e7a0008d21fb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
