name = "KasuKasualPack"
author = "Kasualidad"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7710401d9698527a3545f222be46233c8d97fdc8a0e922a75ee33152c065e5de"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
