name = "KasuKasualPack"
author = "Kasualidad"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb65e2c833a656562e7f10efbad291a2ae5682d49947c19c168d013174f604c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

